#!/usr/bin/env python3
"""
Pre-deployment verification script
Checks if the application is ready for Render deployment
"""

import sys
import os
from pathlib import Path

def check_file_exists(filepath, required=True):
    """Check if a file exists"""
    exists = Path(filepath).exists()
    status = "✅" if exists else ("❌" if required else "⚠️")
    print(f"{status} {filepath} {'(required)' if required else '(optional)'}")
    return exists if required else True

def check_directory_exists(dirpath):
    """Check if a directory exists"""
    exists = Path(dirpath).exists()
    status = "✅" if exists else "❌"
    print(f"{status} {dirpath}/")
    return exists

def check_import(module_name):
    """Check if a module can be imported"""
    try:
        __import__(module_name)
        print(f"✅ {module_name}")
        return True
    except ImportError:
        print(f"❌ {module_name} - not installed")
        return False

def main():
    print("🔍 Render Deployment Verification\n")
    
    all_checks = []
    
    # 1. Check deployment files
    print("📁 Deployment Files:")
    all_checks.append(check_file_exists("render.yaml"))
    all_checks.append(check_file_exists("backend/requirements.txt"))
    all_checks.append(check_file_exists("backend/Procfile"))
    all_checks.append(check_file_exists("backend/runtime.txt"))
    all_checks.append(check_file_exists("backend/.renderignore", required=False))
    all_checks.append(check_file_exists("RENDER_DEPLOYMENT.md", required=False))
    print()
    
    # 2. Check backend structure
    print("🔧 Backend Structure:")
    all_checks.append(check_file_exists("backend/app.py"))
    all_checks.append(check_file_exists("backend/config.py"))
    all_checks.append(check_file_exists("backend/business_intelligence.py"))
    all_checks.append(check_file_exists("backend/business_api.py"))
    all_checks.append(check_directory_exists("backend/uploads"))
    all_checks.append(check_directory_exists("backend/outputs"))
    print()
    
    # 3. Check frontend structure
    print("🎨 Frontend Structure:")
    all_checks.append(check_file_exists("frontend/index.html"))
    print()
    
    # 4. Check Python dependencies
    print("📦 Python Dependencies:")
    os.chdir("backend")
    dependencies = [
        "flask",
        "flask_cors",
        "fitz",
        "PIL",
        "numpy",
        "gunicorn",
        "waitress"
    ]
    for dep in dependencies:
        all_checks.append(check_import(dep))
    os.chdir("..")
    print()
    
    # 5. Check environment variables
    print("🔐 Environment Configuration:")
    env_vars = {
        "FLASK_ENV": "Optional - defaults to development",
        "SECRET_KEY": "Will be auto-generated by Render",
        "MAX_CONTENT_LENGTH": "Optional - defaults to 50MB",
        "CORS_ORIGINS": "Optional - defaults to *",
        "LOG_LEVEL": "Optional - defaults to INFO"
    }
    for var, desc in env_vars.items():
        value = os.environ.get(var)
        if value:
            print(f"✅ {var}={value}")
        else:
            print(f"ℹ️  {var} - {desc}")
    print()
    
    # 6. Test imports
    print("🧪 Testing Application Imports:")
    os.chdir("backend")
    try:
        from config import get_config
        config = get_config()
        print(f"✅ Config loaded: {config.__class__.__name__}")
        all_checks.append(True)
    except Exception as e:
        print(f"❌ Config import failed: {e}")
        all_checks.append(False)
    
    try:
        from business_intelligence import LeaseAnalysisEngine
        engine = LeaseAnalysisEngine()
        print(f"✅ Business Intelligence Engine loaded")
        all_checks.append(True)
    except Exception as e:
        print(f"❌ BI Engine import failed: {e}")
        all_checks.append(False)
    os.chdir("..")
    print()
    
    # 7. Check render.yaml configuration
    print("📋 Render Configuration:")
    try:
        import yaml
        with open("render.yaml", "r") as f:
            render_config = yaml.safe_load(f)
            services = render_config.get("services", [])
            print(f"✅ Found {len(services)} service(s) in render.yaml")
            for service in services:
                print(f"   - {service.get('name', 'unnamed')} ({service.get('type', 'unknown')})")
            all_checks.append(True)
    except ImportError:
        print("⚠️  PyYAML not installed - skipping render.yaml validation")
    except Exception as e:
        print(f"⚠️  Could not parse render.yaml: {e}")
    print()
    
    # Summary
    print("=" * 50)
    passed = sum(all_checks)
    total = len(all_checks)
    percentage = (passed / total * 100) if total > 0 else 0
    
    if percentage == 100:
        print(f"✅ All checks passed! ({passed}/{total})")
        print("🚀 Ready for Render deployment!")
        print("\nNext steps:")
        print("1. git add .")
        print("2. git commit -m 'Prepare for Render deployment'")
        print("3. git push origin main")
        print("4. Deploy via Render Dashboard using Blueprint (render.yaml)")
        return 0
    elif percentage >= 80:
        print(f"⚠️  Most checks passed ({passed}/{total} - {percentage:.0f}%)")
        print("🟡 Ready for deployment with minor warnings")
        return 0
    else:
        print(f"❌ Some checks failed ({passed}/{total} - {percentage:.0f}%)")
        print("⛔ Fix the issues above before deploying")
        return 1

if __name__ == "__main__":
    sys.exit(main())
